on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build/test/push (latest)
jobs:

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.config.tag_prefix}}${{ matrix.config.product}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'rstudio-workbench', dir: 'workbench', os: 'bionic/amd64', prefix: RSW, version: 'latest'}
          - {product: 'rstudio-connect', dir: 'connect', prefix: RSC, version: 'latest'}
          - {product: 'rstudio-connect-content-init', dir: 'connect-content-init', prefix: RSC, version: 'latest'}
          - {product: 'rstudio-package-manager', dir: 'package-manager', prefix: RSPM, version: 'latest'}
          - {product: 'r-session-complete', tag_prefix: 'bionic-', dir: 'r-session-complete/bionic', os: 'bionic/amd64', prefix: RSW, version: 'latest'}
          - {product: 'r-session-complete', tag_prefix: 'centos7-', dir: 'r-session-complete/centos7', os: 'centos7/x86_64', prefix: RSW, version: 'latest'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version
        id: version
        run: |
          # NOTE: --local ensures that "latest" builds use the version in our Makefile (instead of latest from the web)
          VERSION=`./get-version.py ${{ matrix.config.product }} --type=${{ matrix.config.version }} --local`
          echo "::set-output name=VERSION::${VERSION}"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.config.dir }}
          file: ./${{ matrix.config.dir }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
            rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ steps.version.outputs.VERSION }}
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
            ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ steps.version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          push: false
          build-args: |
            RSW_VERSION=${{ steps.version.outputs.VERSION }}
            RSC_VERSION=${{ steps.version.outputs.VERSION }}
            RSPM_VERSION=${{ steps.version.outputs.VERSION }}
            # TODO: need a better way to handle pivoting DOWNLOAD_URL for OS
            RSP_DOWNLOAD_URL=https://download2.rstudio.org/server/${{ matrix.config.os }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Show image size
        run: |
          docker image ls

      - name: Test image
        env:
          IMAGE_NAME: rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          # because we cannot dynamically set env var names... set them all...
          RSW_VERSION: ${{ steps.version.outputs.VERSION }}
          RSC_VERSION: ${{ steps.version.outputs.VERSION }}
          RSPM_VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          docker-compose -f ./${{ matrix.config.dir }}/docker-compose.test.yml run sut

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s) to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          docker push rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ steps.version.outputs.VERSION }}
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ matrix.config.version }}
          docker push ghcr.io/rstudio/${{ matrix.config.product }}:${{ matrix.config.tag_prefix }}${{ steps.version.outputs.VERSION }}
