on:
  schedule:
    # every morning at 8am UTC
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 8 * * *'
  push:
    branches:
      - main
      - dev
      - dev-rspm
  pull_request:

name: build/test/push (preview)
jobs:


  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.config.product }}:${{ matrix.config.type }}:${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
         - {product: "workbench", type: "daily", os: "ubuntu1804"}
         - {product: "workbench", type: "daily", os: "ubuntu2204"}
         - {product: "workbench", type: "preview", os: "ubuntu1804"}
         - {product: "workbench", type: "preview", os: "ubuntu2204"}
         - {product: "connect", type: "daily", os: "ubuntu1804"}
         - {product: "connect", type: "daily", os: "ubuntu2204"}
         - {product: "connect-content-init", type: "daily", os: "ubuntu1804"}
         - {product: "connect-content-init", type: "daily", os: "ubuntu2204"}
         - {product: "package-manager", type: "daily", os: "ubuntu1804"}
         - {product: "package-manager", type: "daily", os: "ubuntu2204"}
         - {product: "package-manager", type: "daily", os: "bionic"}
         - {product: "r-session-complete", type: "daily", os: "ubuntu1804"}
         - {product: "r-session-complete", type: "daily", os: "ubuntu2204"}
         - {product: "r-session-complete", type: "daily", os: "centos7"}
         - {product: "r-session-complete", type: "preview", os: "ubuntu1804"}
         - {product: "r-session-complete", type: "preview", os: "ubuntu2204"}
         - {product: "r-session-complete", type: "preview", os: "centos7"}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '1.11.0'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get Version
        id: get-version
        run: |
          VERSION=`just -f ci.Justfile get-version ${{ matrix.config.product }} --type=${{ matrix.config.type }} --local`
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Image
        id: build-image
        run: |
          TAGS=`just -f ci.Justfile BUILDX_PATH=${{ steps.buildx.outputs.name }} build-preview ${{ matrix.config.type }} ${{ matrix.config.product }} ${{ matrix.config.os }} ${{ steps.get-version.outputs.VERSION }}`
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Show image size
        run: |
          docker image ls

      - name: Test image
        env:
          RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
          RSPM_LICENSE: ${{ secrets.RSPM_LICENSE }}
          RSW_LICENSE: ${{ secrets.RSW_LICENSE }}
        run: |
          just test-image ${{ matrix.config.product }} ${{  steps.get-version.outputs.VERSION }} ${{ steps.build-image.outputs.TAGS }}

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s) to registries
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/dev-rspm' }}
        run: |
          just -f ci.Justfile push-images ${{ steps.build-image.outputs.TAGS }}
