on:
  push:
    branches:
      - main
      - dev
  pull_request:

name: build/test/push (latest)
jobs:

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.config.product }}-${{ matrix.config.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {product: 'workbench', os: 'bionic'}
          - {product: 'connect', os: 'bionic'}
          - {product: 'connect-content-init', os: 'bionic'}
          - {product: 'package-manager', os: 'bionic'}
          - {product: 'r-session-complete', os: 'bionic'}
          - {product: 'r-session-complete', os: 'centos7'}
          - {product: 'workbench-for-microsoft-azure-ml', os: 'bionic'}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get Version
        id: get-version
        run: |
          VERSION=`just get-version ${{ matrix.config.product }} --type=release --local`
          echo "::set-output name=VERSION::$VERSION"

      - name: Build Image
        id: build-image
        run: |
          TAGS=`make BUILDX_PATH=${{ steps.buildx.outputs.name }} PRODUCT=${{ matrix.config.product }} IMAGE_OS=${{ matrix.config.os }} VERSION=${{ steps.get-version.outputs.VERSION }} build`
          echo "::set-output name=TAGS::$TAGS"

      - name: Show image size
        run: |
          docker image ls

      - name: Test image
        env:
          RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
          RSPM_LICENSE: ${{ secrets.RSPM_LICENSE }}
          RSW_LICENSE: ${{ secrets.RSW_LICENSE }}
        run: |
          just test-image ${{ matrix.config.product }} ${{  steps.get-version.outputs.VERSION }} ${{ steps.build-image.outputs.TAGS }}

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.build-image.outputs.TAGS }}
          args: --file=./${{ matrix.config.product }}/Dockerfile.${{ matrix.config.os }}
          command: monitor

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_PAT }}

      - name: Push image(s) to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          just push-images ${{ steps.build-image.outputs.TAGS }}
